name: Deploy

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: evm-balances-api

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy \
          --access-token $FLY_API_TOKEN \
          --app $FLY_APP_NAME \
          --dockerfile ./Dockerfile \
          --remote-only \
          --no-cache \
          --detach
